---
- hosts: localhost
  vars_files: 
    - secret.yml
  tasks:
  - name: Kube-master node provisioning
    ec2:
      image: ami-08e0ca9924195beba
      instance_type: t2.micro
      count: 1
      instance_tags:
        Name: kube-master
      group_id: sg-016a7bc328d400c91
      key_name: MyKeyPair
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      region: ap-south-1
      
  - name: Kube-worker node provisioning
    ec2:
      image: ami-08e0ca9924195beba
      instance_type: t2.micro
      count: 1
      instance_tags:
        Name: kube-worker
      group_id: sg-016a7bc328d400c91
      key_name: MyKeyPair
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      region: ap-south-1 
